# 语言文本字典
texts = {
    "zh_CN": {
        "app_title": "PyQuick - Python安装与管理工具",
        "settings": "设置",
        "language_settings": "语言设置",
        "simplified_chinese": "简体中文",
        "english": "English",
        "theme_settings": "主题设置",
        "light_theme": "浅色主题",
        "dark_theme": "深色主题",
        "download_mirror_settings": "下载镜像设置",
        "python_download_mirror": "Python下载镜像:",
        "default_source": "默认源",
        "pip_mirror": "Pip镜像源:",
        "log_settings": "日志设置",
        "max_log_size": "最大日志大小(MB):",
        "download_settings": "下载设置",
        "enable_multithreading": "启用多线程下载",
        "enable_pip_version_check": "自动检查Pip更新",
        "cancel": "取消",
        "save": "保存",
        "success": "成功",
        "settings_saved": "设置已保存",
        "warning": "警告",
        "warning_code": "警告 0x0000300B",
        "save_failed": "保存设置失败: {}",
        "language_changed": "语言设置已更改，应用程序将自动重启以应用新的语言设置",
        "restart_now": "是否立即重启应用程序？",
        "update_language_failed": "更新界面语言失败：{}",
        "restart_recommended": "建议重启应用程序",
        "settings_read_fail": "读取设置失败",
        "settings_save_fail": "保存设置失败",
        
        # 主界面文本
        "python_download": "Python下载",
        "pip_management": "Pip管理",
        "select_python_version": "选择Python版本:",
        "reload": "刷新",
        "select_destination": "选择目标路径:",
        "select_path": "选择路径",
        "select_threads": "选择线程数:",
        "select_thread_number": "选择线程数:",
        "choose_download_file": "选择下载文件:",
        "download": "下载",
        "cancel_download": "取消下载",
        "pause_download": "暂停下载",
        "resume_download": "继续下载",
        
        # Pip管理
        "pip_version": "Pip版本:",
        "retry": "重试",
        "enter_package_name": "输入包名称:",
        "install_package": "安装包",
        "uninstall_package": "卸载包",
        "upgrade_package": "升级包",
        
        # 菜单
        "settings_menu": "设置",
        "help_menu": "帮助",
        "about": "关于",
        "debug_info": "调试信息",
        
        # 对话框
        "error": "错误",
        "warning_msg": "警告",
        "info": "信息",
        "exit": "退出",
        "do_you_want_to_quit": "确定要退出吗？",
        
        # 调试信息
        "system_info": "系统信息",
        "app_info": "应用信息",
        "app_warning": "应用警告",
        "app_info_log": "应用信息",
        "log_info": "日志信息",
        "network_diagnostics": "网络诊断",
        "close": "关闭",
        "run_diagnostics": "运行网络诊断",
        "refresh_info": "刷新信息",
        "log_filter": "日志过滤:",
        "show_errors_only": "只显示错误",
        "show_errors_warnings": "显示错误和警告",
        "show_all_logs": "显示所有日志",
        "refresh_log": "刷新日志",
        "app_info_title": "应用程序信息",
        "app_name": "应用名称: ",
        "app_version": "应用版本: ",
        "config_path": "配置路径: ",
        "working_dir": "工作目录: ",
        "config_file_info": "配置文件信息",
        "multithread_enabled": "多线程启用: ",
        "multithread_config": "多线程配置: ",
        "multithread_read_fail": "多线程配置读取失败: ",
        "theme": "主题: ",
        "theme_read_fail": "主题配置读取失败: ",
        "python_mirror": "Python镜像: ",
        "python_mirror_read_fail": "Python镜像配置读取失败: ",
        "pip_mirror_config": "Pip镜像: ",
        "pip_mirror_read_fail": "Pip镜像配置读取失败: ",
        "language_setting": "语言设置: ",
        "language_read_fail": "语言配置读取失败: ",
        "log_size_limit": "日志大小限制: ",
        "log_size_read_fail": "日志大小配置读取失败: ",
        "basic_system_info": "系统基本信息",
        "os": "操作系统: ",
        "system_arch": "系统架构: ",
        "processor": "处理器: ",
        "python_version": "Python版本: ",
        "tkinter_version": "Tkinter版本: ",
        "cpu_cores": "CPU核心数: ",
        "physical_cores": "物理",
        "logical_cores": "逻辑",
        "realtime_system_info": "实时系统信息 (每秒更新)",
        "cpu_usage": "CPU使用率: ",
        "memory": "内存: ",
        "pyquick_memory": "PyQuick内存占用: ",
        "disk": "磁盘: ",
        "latest_log_file": "最新日志文件: ",
        "log_entries": "日志条目 (已过滤 - {})",
        "no_log_entries": "没有符合过滤条件的日志条目 ({})",
        "no_log_files": "未找到日志文件。",
        "no_log_dir": "日志目录不存在。",
        "log_read_error": "读取日志文件时出错: {}",
        "config_not_found": "未找到配置文件",
        
        # 镜像测试
        "test_python_mirror": "测试Python镜像",
        "test_pip_mirror": "测试Pip镜像",
        "test_mirror_delay": "测试{}镜像延迟",
        "mirror_address": "镜像地址",
        "delay": "延迟",
        "status": "状态",
        "ready_to_test": "准备测试...",
        "testing": "正在测试: {}",
        "test_completed": "测试完成",
        "start_test": "开始测试",
        "set_best_mirror": "设为最佳镜像",
        "add_custom_mirror": "添加自定义镜像",
        "add": "添加",
        "mirror_url": "镜像URL:",
        "enter_valid_mirror": "请输入有效的镜像URL",
        "url_format_error": "URL必须以http://或https://开头",
        "custom_mirror_added": "自定义镜像已添加",
        "mirror_exists": "镜像已存在或添加失败",
        "set_mirror_success": "{} 最佳镜像设置为: {}",
        "mirror_deleted": "已删除镜像: {}",
        "mirror_connection_failed": "镜像 {} 连接失败。是否从列表中删除?",
        "mirror_connection_success_but_download_failed": "镜像 {} 连接成功但无法下载包。是否从列表中删除?",
        "read_custom_python_mirror_failed": "读取自定义Python镜像源失败: {}",
        "read_custom_pip_mirror_failed": "读取自定义Pip镜像源失败: {}",
        "save_custom_python_mirror_failed": "保存自定义Python镜像源失败: {}",
        "save_custom_pip_mirror_failed": "保存自定义Pip镜像源失败: {}",
        "mirror_connection_test_failed": "镜像连接测试失败，状态码: {}",
        "mirror_connection_test_exception": "镜像连接测试异常: {}",
        "mirror_download_test_exception": "镜像下载测试异常: {}",
        "ready_to_test": "准备测试...",
        "connect_ok_but_download_failed": "连接OK但下载失败",
        "normal": "正常",
        "failed": "失败",
        "timeout": "超时",
        "second": "秒",
        
        # 下载状态
        "downloading": "正在下载",
        "download_paused": "下载已暂停",
        "download_cancelled": "下载已取消",
        "download_completed": "下载完成!",
        "download_failed": "下载失败: {}",
        "file_exists": "文件已存在，是否替换？",
        "failed_to_create_dir": "无法创建目录: {}",
        "failed_to_remove_file": "无法删除现有文件: {}",
        "finding_mirror": "寻找可用的下载镜像...",
        "failed_to_find_mirror": "无法找到可用的下载镜像",
        "starting_download": "开始下载: {}",
        "loading_files": "正在加载文件列表...",
        "found_files": "找到 {} 个可下载的文件",
        "no_files_found": "没有找到可用的文件",
        "loading_file_failed": "加载文件列表失败: {}",
        
        # 网络诊断
        "network_test_ready": "就绪",
        "network_test_initializing": "初始化中...",
        "network_test_preparing": "正在准备网络诊断...",
        "network_test_results": "网络诊断结果",
        "network_test_time": "测试时间: {}",
        "network_test_in_progress": "测试中 ({}/{})：{}",
        "network_test_site": "测试 {}/{}: {}...",
        "network_test_paused": "暂停中...",
        "network_test_status_normal": "正常",
        "network_test_status_error": "错误",
        "network_test_status_code": "(状态码: {})",
        "network_test_response_time": "   响应时间: {:.2f} 秒",
        "network_test_status_failed": "失败",
        "network_test_error": "   错误: {}",
        "network_test_canceled": "测试已取消！",
        "network_test_completed": "所有测试已完成！",
        "network_test_status_canceled": "已取消",
        "network_test_status_completed": "测试完成",
        "start_test": "开始测试",
        "pause_test": "暂停测试",
        "resume_test": "继续测试",
        "cancel_test": "取消测试",
        
        # 主题相关
        "theme_setting": "主题: ",
        "theme_read_fail": "主题配置读取失败: ",
        "select_python_version_first": "请先选择Python版本",
        "select_download_file": "请选择下载文件",
        "select_destination_dir": "请选择目标目录",
        "failed_to_get_file_size": "无法获取文件大小",
        "download_start_failed": "启动下载失败: {}",
        "cancel_error": "取消下载时出错: {}",
        "enter_package_name_first": "请输入包名称",
        "sorting": "排序中...",
        "no_python_versions": "未找到任何Python版本，请检查网络连接或更换镜像源",
        "python_version_load_failed": "加载Python版本列表失败: {}",
        "pip_checking": "检查中...",
        "pip_up_to_date": "Pip已是最新版本({}, 版本:{})",
        "pip_new_version_available": "有新版本可用({}:{}-->{})",
        "failed_to_get_pip_version": "获取Pip版本失败",
        "select_pip_version": "选择Pip版本:",
        "pip_not_found": "未找到选择的Pip版本",
        "package_install_success": "{} 安装成功",
        "package_install_failed": "安装失败: {}",
        "package_install_error": "安装出错: {}",
        "package_uninstall_confirm": "确定要卸载 {} 吗?",
        "package_uninstall_success": "{} 卸载成功",
        "package_uninstall_failed": "卸载失败: {}",
        "package_uninstall_error": "卸载出错: {}",
    },
    "en_US": {
        "app_title": "PyQuick - Python Installation and Management Tool",
        "settings": "Settings",
        "language_settings": "Language Settings",
        "simplified_chinese": "Simplified Chinese",
        "english": "English",
        "theme_settings": "Theme Settings",
        "light_theme": "Light Theme",
        "dark_theme": "Dark Theme",
        "download_mirror_settings": "Download Mirror Settings",
        "python_download_mirror": "Python Download Mirror:",
        "default_source": "Default Source",
        "pip_mirror": "Pip Mirror:",
        "log_settings": "Log Settings",
        "max_log_size": "Max Log Size(MB):",
        "download_settings": "Download Settings",
        "enable_multithreading": "Enable Multithreading",
        "enable_pip_version_check": "Auto Check Pip Update",
        "cancel": "Cancel",
        "save": "Save",
        "success": "Success",
        "settings_saved": "Settings saved",
        "warning": "Warning",
        "warning_code": "Warning 0x0000300B",
        "save_failed": "Failed to save settings: {}",
        "language_changed": "Language setting has been changed, the application will restart automatically to apply the new language settings",
        "restart_now": "Do you want to restart the application now?",
        "update_language_failed": "Failed to update interface language: {}",
        "restart_recommended": "It is recommended to restart the application",
        "settings_read_fail": "Failed to read settings",
        "settings_save_fail": "Failed to save settings",
        
        # 主界面
        "python_download": "Python Download",
        "pip_management": "Pip Management",
        "select_python_version": "Select Python Version:",
        "reload": "Reload",
        "select_destination": "Select Destination:",
        "select_path": "Select Path",
        "select_threads": "Select Thread Count:",
        "select_thread_number": "Select Thread Count:",
        "choose_download_file": "Choose Download File:",
        "download": "Download",
        "cancel_download": "Cancel Download",
        "pause_download": "Pause Download",
        "resume_download": "Resume Download",
        
        # Pip管理
        "pip_version": "Pip Version:",
        "retry": "Retry",
        "enter_package_name": "Enter Package Name:",
        "install_package": "Install Package",
        "uninstall_package": "Uninstall Package",
        "upgrade_package": "Upgrade Package",
        
        # 菜单
        "settings_menu": "Settings",
        "help_menu": "Help",
        "about": "About",
        "debug_info": "Debug Info",
        
        # Dialogs
        "error": "Error",
        "warning_msg": "Warning",
        "info": "Information",
        "exit": "Exit",
        "do_you_want_to_quit": "Are you sure you want to quit?",
        
        # 调试信息
        "system_info": "System Info",
        "app_info": "Application Info",
        "app_warning": "Application Warning",
        "app_info_log": "Application Info",
        "log_info": "Log Info",
        "network_diagnostics": "Network Diagnostics",
        "close": "Close",
        "run_diagnostics": "Run Network Diagnostics",
        "refresh_info": "Refresh Info",
        "log_filter": "Log Filter:",
        "show_errors_only": "Show Errors Only",
        "show_errors_warnings": "Show Errors and Warnings",
        "show_all_logs": "Show All Logs",
        "refresh_log": "Refresh Log",
        "app_info_title": "Application Information",
        "app_name": "App Name: ",
        "app_version": "App Version: ",
        "config_path": "Config Path: ",
        "working_dir": "Working Directory: ",
        "config_file_info": "Configuration Files Info",
        "multithread_enabled": "Multithreading Enabled: ",
        "multithread_config": "Multithreading Config: ",
        "multithread_read_fail": "Failed to read multithreading config: ",
        "theme": "Theme: ",
        "theme_read_fail": "Failed to read theme config: ",
        "python_mirror": "Python Mirror: ",
        "python_mirror_read_fail": "Failed to read Python mirror config: ",
        "pip_mirror_config": "Pip Mirror: ",
        "pip_mirror_read_fail": "Failed to read Pip mirror config: ",
        "language_setting": "Language Setting: ",
        "language_read_fail": "Failed to read language config: ",
        "log_size_limit": "Log Size Limit: ",
        "log_size_read_fail": "Failed to read log size config: ",
        "basic_system_info": "Basic System Information",
        "os": "Operating System: ",
        "system_arch": "System Architecture: ",
        "processor": "Processor: ",
        "python_version": "Python Version: ",
        "tkinter_version": "Tkinter Version: ",
        "cpu_cores": "CPU Cores: ",
        "physical_cores": "physical",
        "logical_cores": "logical",
        "realtime_system_info": "Real-time System Info (Updated every second)",
        "cpu_usage": "CPU Usage: ",
        "memory": "Memory: ",
        "pyquick_memory": "PyQuick Memory Usage: ",
        "disk": "Disk: ",
        "latest_log_file": "Latest Log File: ",
        "log_entries": "Log Entries (Filtered - {})",
        "no_log_entries": "No log entries match the filter ({})",
        "no_log_files": "No log files found.",
        "no_log_dir": "Log directory doesn't exist.",
        "log_read_error": "Error reading log file: {}",
        "config_not_found": "Config file not found",
        
        # Mirror testing
        "test_python_mirror": "Test Python Mirror",
        "test_pip_mirror": "Test Pip Mirror",
        "test_mirror_delay": "Test {} Mirror Delay",
        "mirror_address": "Mirror Address",
        "delay": "Delay",
        "status": "Status",
        "ready_to_test": "Ready to test...",
        "testing": "Testing: {}",
        "test_completed": "Test completed",
        "start_test": "Start Test",
        "set_best_mirror": "Set as Best Mirror",
        "add_custom_mirror": "Add Custom Mirror",
        "add": "Add",
        "mirror_url": "Mirror URL:",
        "enter_valid_mirror": "Please enter a valid mirror URL",
        "url_format_error": "URL must start with http:// or https://",
        "custom_mirror_added": "Custom mirror added",
        "mirror_exists": "Mirror already exists or failed to add",
        "set_mirror_success": "{} best mirror set: {}",
        "mirror_deleted": "Mirror deleted: {}",
        "mirror_connection_failed": "Mirror {} connection failed. Do you want to remove it from the list?",
        "mirror_connection_success_but_download_failed": "Mirror {} connected successfully but failed to download packages. Do you want to remove it from the list?",
        "read_custom_python_mirror_failed": "Failed to read custom Python mirror: {}",
        "read_custom_pip_mirror_failed": "Failed to read custom Pip mirror: {}",
        "save_custom_python_mirror_failed": "Failed to save custom Python mirror: {}",
        "save_custom_pip_mirror_failed": "Failed to save custom Pip mirror: {}",
        "mirror_connection_test_failed": "Mirror connection test failed, status code: {}",
        "mirror_connection_test_exception": "Mirror connection test exception: {}",
        "mirror_download_test_exception": "Mirror download test exception: {}",
        "ready_to_test": "Ready to test...",
        "connect_ok_but_download_failed": "Connection OK but download failed",
        "normal": "Normal",
        "failed": "Failed",
        "timeout": "Timeout",
        "second": "s",
        
        # Download status
        "downloading": "Downloading",
        "download_paused": "Download paused",
        "download_cancelled": "Download cancelled",
        "download_completed": "Download completed!",
        "download_failed": "Download failed: {}",
        "file_exists": "File already exists. Do you want to replace it?",
        "failed_to_create_dir": "Failed to create directory: {}",
        "failed_to_remove_file": "Failed to remove existing file: {}",
        "finding_mirror": "Finding available download mirrors...",
        "failed_to_find_mirror": "Failed to find a working download mirror",
        "starting_download": "Starting download: {}",
        "loading_files": "Loading file list...",
        "found_files": "Found {} downloadable files",
        "no_files_found": "No files found",
        "loading_file_failed": "Failed to load file list: {}",
        
        # 网络诊断
        "network_test_ready": "Ready",
        "network_test_initializing": "Initializing...",
        "network_test_preparing": "Preparing network diagnostics...",
        "network_test_results": "Network Diagnostics Results",
        "network_test_time": "Test time: {}",
        "network_test_in_progress": "Testing ({}/{})：{}",
        "network_test_site": "Testing {}/{}: {}...",
        "network_test_paused": "Paused...",
        "network_test_status_normal": "Normal",
        "network_test_status_error": "Error",
        "network_test_status_code": "(Status code: {})",
        "network_test_response_time": "   Response time: {:.2f} seconds",
        "network_test_status_failed": "Failed",
        "network_test_error": "   Error: {}",
        "network_test_canceled": "Test canceled!",
        "network_test_completed": "All tests completed!",
        "network_test_status_canceled": "Canceled",
        "network_test_status_completed": "Tests completed",
        "start_test": "Start Test",
        "pause_test": "Pause Test",
        "resume_test": "Resume Test",
        "cancel_test": "Cancel Test",
        
        # 主题相关
        "theme_setting": "Theme: ",
        "theme_read_fail": "Theme configuration read failed: ",
        "select_python_version_first": "Please select a Python version first",
        "select_download_file": "Please select a download file",
        "select_destination_dir": "Please select a destination directory",
        "failed_to_get_file_size": "Failed to get file size",
        "download_start_failed": "Failed to start download: {}",
        "cancel_error": "Error while canceling download: {}",
        "enter_package_name_first": "Please enter a package name",
        "sorting": "Sorting...",
        "no_python_versions": "No Python versions found, please check your network connection or change the mirror source",
        "python_version_load_failed": "Failed to load Python version list: {}",
        "pip_checking": "Checking...",
        "pip_up_to_date": "Pip is up to date({}, Ver:{})",
        "pip_new_version_available": "New version available({}:{}-->{})",
        "failed_to_get_pip_version": "Failed to get pip version",
        "select_pip_version": "Select Pip Version:",
        "pip_not_found": "Selected Pip version not found",
        "package_install_success": "{} installed successfully",
        "package_install_failed": "Installation failed: {}",
        "package_install_error": "Installation error: {}",
        "package_uninstall_confirm": "Are you sure you want to uninstall {}?",
        "package_uninstall_success": "{} uninstalled successfully",
        "package_uninstall_failed": "Uninstallation failed: {}",
        "package_uninstall_error": "Uninstallation error: {}",
    }
}

current_language = "zh_CN"  # 默认语言

def set_language(lang):
    """设置当前语言"""
    global current_language
    if lang in texts:
        current_language = lang
        return True
    return False

def get_text(key):
    """获取当前语言的文本"""
    global current_language
    if current_language not in texts:
        current_language = "zh_CN"  # 如果设置的语言不存在，使用默认语言
    
    lang_texts = texts[current_language]
    return lang_texts.get(key, key)  # 如果找不到对应文本，返回键值本身 