"""
PyQuick Requirements 模块

提供处理requirements.txt文件的功能，包括导入和导出pip包列表
"""
import os
import sys
import tkinter as tk
from tkinter import ttk, filedialog, messagebox
import subprocess
import threading
import re
from typing import List, Dict, Tuple, Optional, Callable, Any

from lang import get_text
from log import get_logger

# 获取日志记录器
logger = get_logger()

def parse_requirements_file(file_path: str) -> List[Dict[str, str]]:
    """
    解析requirements.txt文件
    
    参数:
        file_path: requirements.txt文件路径
    
    返回:
        List[Dict]: 包含包信息的列表，每个包是一个字典，格式为{"name": 包名, "version": 版本约束}
    """
    packages = []
    
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            for line in f:
                # 去除注释和空白
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                
                # 处理包含注释的行
                if '#' in line:
                    line = line.split('#')[0].strip()
                
                # 尝试解析包名和版本
                # 支持各种格式：
                # package==1.0.0
                # package>=1.0.0,<2.0.0
                # package~=1.0.0
                # package
                # -e git+https://...
                if line.startswith('-e') or line.startswith('--editable'):
                    # 可编辑包，暂不处理
                    logger.warning(f"跳过可编辑包: {line}")
                    continue
                
                if line.startswith('-r') or line.startswith('--requirement'):
                    # 嵌套的requirements文件，暂不处理
                    logger.warning(f"跳过嵌套requirements: {line}")
                    continue
                
                # 解析包名和版本约束
                match = re.match(r'^([a-zA-Z0-9_\-\.]+)(.*)$', line)
                if match:
                    name = match.group(1)
                    version_spec = match.group(2).strip()
                    
                    packages.append({
                        "name": name,
                        "version": version_spec
                    })
                else:
                    logger.warning(f"无法解析包: {line}")
    except Exception as e:
        logger.error(f"解析requirements.txt失败: {str(e)}")
    
    return packages

def export_requirements(python_path: str, output_path: str) -> bool:
    """
    导出当前Python环境中已安装的包为requirements.txt
    
    参数:
        python_path: Python解释器路径
        output_path: 输出文件路径
    
    返回:
        bool: 是否成功导出
    """
    try:
        # 运行pip freeze命令获取已安装的包
        result = subprocess.run(
            [python_path, "-m", "pip", "freeze"],
            capture_output=True,
            text=True,
            encoding="utf-8"
        )
        
        if result.returncode != 0:
            logger.error(f"执行pip freeze失败: {result.stderr}")
            return False
        
        # 写入requirements.txt文件
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write("# Generated by PyQuick\n")
            f.write("# Python version: " + get_python_version(python_path) + "\n\n")
            f.write(result.stdout)
        
        return True
    except Exception as e:
        logger.error(f"导出requirements.txt失败: {str(e)}")
        return False

def get_python_version(python_path: str) -> str:
    """
    获取Python版本
    
    参数:
        python_path: Python解释器路径
    
    返回:
        str: Python版本
    """
    try:
        result = subprocess.run(
            [python_path, "--version"],
            capture_output=True,
            text=True,
            encoding="utf-8"
        )
        
        if result.returncode != 0:
            return "Unknown"
        
        # 从输出中提取版本号
        version_match = re.search(r'Python\s+(\d+\.\d+\.\d+)', result.stdout)
        if version_match:
            return version_match.group(1)
        else:
            return "Unknown"
    except Exception:
        return "Unknown"

class ImportRequirementsWindow:
    """导入requirements.txt窗口类"""
    
    def __init__(self, parent, python_path: str):
        """
        初始化导入窗口
        
        参数:
            parent: 父窗口
            python_path: Python解释器路径
        """
        self.parent = parent
        self.python_path = python_path
        self.window = None
        self.requirements_path = None
        self.packages = []
        self.selected_packages = set()
        
        # 创建导入窗口
        self.create_import_window()
    
    def create_import_window(self):
        """创建导入窗口"""
        # 如果窗口已存在，不再创建
        if self.window is not None and self.window.winfo_exists():
            self.window.lift()
            return
        
        # 创建导入窗口
        self.window = tk.Toplevel(self.parent)
        self.window.title(get_text("import_requirements"))
        self.window.minsize(600, 400)
        
        # 设置为模态窗口
        self.window.transient(self.parent)
        self.window.grab_set()
        
        # 创建主框架
        main_frame = ttk.Frame(self.window, padding=20)
        main_frame.pack(fill="both", expand=True)
        
        # 文件选择框架
        file_frame = ttk.Frame(main_frame)
        file_frame.pack(fill="x", pady=(0, 10))
        
        # 文件路径
        self.file_path_var = tk.StringVar()
        ttk.Label(file_frame, text=get_text("requirements_file")).pack(side="left", padx=(0, 5))
        ttk.Entry(file_frame, textvariable=self.file_path_var, width=50).pack(side="left", padx=(0, 5), fill="x", expand=True)
        ttk.Button(
            file_frame, 
            text=get_text("browse"),
            command=self.browse_file
        ).pack(side="left")
        
        # 创建包列表框架
        list_frame = ttk.LabelFrame(main_frame, text=get_text("package_list"), padding=10)
        list_frame.pack(fill="both", expand=True, pady=(0, 10))
        
        # 包列表
        columns = ("name", "version")
        self.package_list = ttk.Treeview(list_frame, columns=columns, show="headings", selectmode="extended")
        self.package_list.heading("name", text=get_text("package_name"))
        self.package_list.heading("version", text=get_text("version_constraint"))
        self.package_list.column("name", width=200)
        self.package_list.column("version", width=200)
        self.package_list.pack(side="left", fill="both", expand=True)
        
        # 滚动条
        scrollbar = ttk.Scrollbar(list_frame, orient="vertical", command=self.package_list.yview)
        scrollbar.pack(side="right", fill="y")
        self.package_list.configure(yscrollcommand=scrollbar.set)
        
        # 绑定选择事件
        self.package_list.bind("<<TreeviewSelect>>", self.on_package_select)
        
        # 选择控制框架
        select_frame = ttk.Frame(main_frame)
        select_frame.pack(fill="x", pady=(0, 10))
        
        # 全选按钮
        ttk.Button(
            select_frame, 
            text=get_text("select_all"),
            command=self.select_all
        ).pack(side="left", padx=(0, 5))
        
        # 取消全选按钮
        ttk.Button(
            select_frame, 
            text=get_text("deselect_all"),
            command=self.deselect_all
        ).pack(side="left", padx=(0, 5))
        
        # 反选按钮
        ttk.Button(
            select_frame, 
            text=get_text("invert_selection"),
            command=self.invert_selection
        ).pack(side="left")
        
        # 选中统计
        self.selection_var = tk.StringVar(value=get_text("selected_packages").format(0, 0))
        ttk.Label(select_frame, textvariable=self.selection_var).pack(side="right")
        
        # 操作按钮框架
        button_frame = ttk.Frame(main_frame)
        button_frame.pack(fill="x", pady=(10, 0))
        
        # 导入按钮
        self.import_button = ttk.Button(
            button_frame, 
            text=get_text("install_selected"),
            command=self.install_packages,
            state="disabled"
        )
        self.import_button.pack(side="left", padx=(0, 5))
        
        # 安装所有按钮
        self.install_all_button = ttk.Button(
            button_frame, 
            text=get_text("install_all"),
            command=lambda: self.install_packages(all_packages=True),
            state="disabled"
        )
        self.install_all_button.pack(side="left", padx=(0, 5))
        
        # 取消按钮
        ttk.Button(
            button_frame, 
            text=get_text("cancel"),
            command=self.window.destroy
        ).pack(side="right")
        
        # 窗口居中
        self.center_window()
        
        # 绑定关闭事件
        self.window.protocol("WM_DELETE_WINDOW", self.window.destroy)
    
    def center_window(self):
        """使窗口居中显示"""
        self.window.update_idletasks()
        width = self.window.winfo_width()
        height = self.window.winfo_height()
        x = (self.window.winfo_screenwidth() // 2) - (width // 2)
        y = (self.window.winfo_screenheight() // 2) - (height // 2)
        self.window.geometry(f"{width}x{height}+{x}+{y}")
    
    def browse_file(self):
        """浏览文件"""
        file_path = filedialog.askopenfilename(
            parent=self.window,
            title=get_text("select_requirements_file"),
            filetypes=[
                (get_text("requirements_files"), "*.txt"),
                (get_text("all_files"), "*.*")
            ]
        )
        
        if file_path:
            self.file_path_var.set(file_path)
            self.requirements_path = file_path
            self.load_requirements()
    
    def load_requirements(self):
        """加载requirements.txt文件"""
        if not self.requirements_path:
            return
        
        # 清空包列表
        for item in self.package_list.get_children():
            self.package_list.delete(item)
        
        self.packages = parse_requirements_file(self.requirements_path)
        self.selected_packages = set()
        
        # 填充包列表
        for i, package in enumerate(self.packages):
            self.package_list.insert("", "end", iid=str(i), values=(package["name"], package["version"]))
        
        # 更新选中统计
        self.update_selection_count()
        
        # 启用按钮
        self.install_all_button.config(state="normal" if self.packages else "disabled")
    
    def on_package_select(self, event):
        """包选择事件处理"""
        selected_items = self.package_list.selection()
        self.selected_packages = set(selected_items)
        
        # 更新选中统计
        self.update_selection_count()
        
        # 更新导入按钮状态
        self.import_button.config(state="normal" if selected_items else "disabled")
    
    def update_selection_count(self):
        """更新选中统计"""
        total = len(self.packages)
        selected = len(self.selected_packages)
        self.selection_var.set(get_text("selected_packages").format(selected, total))
    
    def select_all(self):
        """全选"""
        for i in range(len(self.packages)):
            self.package_list.selection_add(str(i))
        
        # 更新选中包集合
        self.selected_packages = set(str(i) for i in range(len(self.packages)))
        
        # 更新选中统计
        self.update_selection_count()
        
        # 更新导入按钮状态
        self.import_button.config(state="normal" if self.packages else "disabled")
    
    def deselect_all(self):
        """取消全选"""
        for i in range(len(self.packages)):
            self.package_list.selection_remove(str(i))
        
        # 更新选中包集合
        self.selected_packages = set()
        
        # 更新选中统计
        self.update_selection_count()
        
        # 更新导入按钮状态
        self.import_button.config(state="disabled")
    
    def invert_selection(self):
        """反选"""
        all_ids = set(str(i) for i in range(len(self.packages)))
        inverted_selection = all_ids - self.selected_packages
        
        # 取消当前选择
        for item in self.selected_packages:
            self.package_list.selection_remove(item)
        
        # 选择反选项
        for item in inverted_selection:
            self.package_list.selection_add(item)
        
        # 更新选中包集合
        self.selected_packages = inverted_selection
        
        # 更新选中统计
        self.update_selection_count()
        
        # 更新导入按钮状态
        self.import_button.config(state="normal" if inverted_selection else "disabled")
    
    def install_packages(self, all_packages=False):
        """
        安装选定的包
        
        参数:
            all_packages: 是否安装所有包
        """
        # 禁用按钮，防止重复点击
        self.import_button.config(state="disabled")
        self.install_all_button.config(state="disabled")
        
        # 确定要安装的包
        if all_packages:
            packages_to_install = self.packages
        else:
            selected_indices = [int(i) for i in self.selected_packages]
            packages_to_install = [self.packages[i] for i in selected_indices]
        
        if not packages_to_install:
            messagebox.showinfo(get_text("info"), get_text("no_packages_selected"))
            
            # 重新启用按钮
            self.import_button.config(state="normal" if self.selected_packages else "disabled")
            self.install_all_button.config(state="normal" if self.packages else "disabled")
            return
        
        # 创建安装确认对话框
        confirm_msg = get_text("confirm_install_packages").format(len(packages_to_install))
        if not messagebox.askyesno(get_text("confirm"), confirm_msg):
            # 重新启用按钮
            self.import_button.config(state="normal" if self.selected_packages else "disabled")
            self.install_all_button.config(state="normal" if self.packages else "disabled")
            return
        
        # 创建安装进度窗口
        progress_window = tk.Toplevel(self.window)
        progress_window.title(get_text("installing_packages"))
        progress_window.resizable(False, False)
        progress_window.transient(self.window)
        progress_window.grab_set()
        
        # 创建主框架
        progress_frame = ttk.Frame(progress_window, padding=20)
        progress_frame.pack(fill="both", expand=True)
        
        # 添加进度信息
        progress_label = ttk.Label(
            progress_frame, 
            text=get_text("installing_please_wait"),
            font=("", 10, "bold")
        )
        progress_label.pack(pady=(0, 10))
        
        # 添加包列表
        package_text = tk.Text(progress_frame, width=60, height=15, wrap="word")
        package_text.pack(fill="both", expand=True, pady=(0, 10))
        
        # 滚动条
        scrollbar = ttk.Scrollbar(package_text, orient="vertical", command=package_text.yview)
        scrollbar.pack(side="right", fill="y")
        package_text.configure(yscrollcommand=scrollbar.set)
        
        # 添加进度条
        progress_var = tk.DoubleVar(value=0)
        progress_bar = ttk.Progressbar(progress_frame, variable=progress_var, maximum=100)
        progress_bar.pack(fill="x", pady=(0, 10))
        
        # 状态标签
        status_var = tk.StringVar(value=get_text("preparing_installation"))
        status_label = ttk.Label(progress_frame, textvariable=status_var)
        status_label.pack(pady=(0, 10))
        
        # 按钮
        cancel_button = ttk.Button(
            progress_frame, 
            text=get_text("cancel"),
            command=lambda: self.abort_installation(progress_window)
        )
        cancel_button.pack()
        
        # 窗口居中
        progress_window.update_idletasks()
        width = progress_window.winfo_width()
        height = progress_window.winfo_height()
        x = (progress_window.winfo_screenwidth() // 2) - (width // 2)
        y = (progress_window.winfo_screenheight() // 2) - (height // 2)
        progress_window.geometry(f"{width}x{height}+{x}+{y}")
        
        # 启动安装线程
        self.abort_flag = False
        threading.Thread(
            target=self.run_installation,
            args=(
                progress_window,
                packages_to_install,
                package_text,
                progress_var,
                status_var,
                cancel_button
            ),
            daemon=True
        ).start()
    
    def abort_installation(self, progress_window):
        """
        中止安装
        
        参数:
            progress_window: 进度窗口
        """
        self.abort_flag = True
        
        # 关闭进度窗口
        progress_window.destroy()
        
        # 重新启用按钮
        self.import_button.config(state="normal" if self.selected_packages else "disabled")
        self.install_all_button.config(state="normal" if self.packages else "disabled")
    
    def run_installation(self, progress_window, packages, text_widget, progress_var, status_var, cancel_button):
        """
        运行安装线程
        
        参数:
            progress_window: 进度窗口
            packages: 要安装的包
            text_widget: 文本控件
            progress_var: 进度变量
            status_var: 状态变量
            cancel_button: 取消按钮
        """
        total_packages = len(packages)
        success_count = 0
        fail_count = 0
        
        for i, package in enumerate(packages):
            # 检查中止标志
            if self.abort_flag:
                break
            
            name = package["name"]
            version = package["version"]
            
            # 更新状态
            current = i + 1
            progress_window.after(0, lambda p=current/total_packages*100: progress_var.set(p))
            progress_window.after(0, lambda s=get_text("installing_package").format(current, total_packages, name): status_var.set(s))
            
            # 构建命令
            cmd = [self.python_path, "-m", "pip", "install"]
            
            # 添加包名和版本约束
            package_spec = name
            if version:
                package_spec += version
            
            cmd.append(package_spec)
            
            # 执行安装
            try:
                process = subprocess.Popen(
                    cmd,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    text=True,
                    encoding="utf-8"
                )
                
                # 读取输出
                stdout, stderr = process.communicate()
                
                # 添加到文本控件
                progress_window.after(0, lambda t=text_widget, n=name, v=version, o=stdout, e=stderr, rc=process.returncode: self.update_text(t, n, v, o, e, rc))
                
                # 更新统计
                if process.returncode == 0:
                    success_count += 1
                else:
                    fail_count += 1
            except Exception as e:
                # 添加到文本控件
                error_message = str(e)
                progress_window.after(0, lambda t=text_widget, n=name, v=version, e=error_message: self.update_text(t, n, v, "", e, 1))
                fail_count += 1
        
        # 安装完成
        progress_window.after(0, lambda: progress_var.set(100))
        
        completion_message = get_text("installation_complete").format(
            total_packages, success_count, fail_count
        )
        
        progress_window.after(0, lambda s=completion_message: status_var.set(s))
        progress_window.after(0, lambda b=cancel_button: b.configure(text=get_text("close")))
        
        # 重新启用按钮
        progress_window.after(0, lambda: self.import_button.config(state="normal" if self.selected_packages else "disabled"))
        progress_window.after(0, lambda: self.install_all_button.config(state="normal" if self.packages else "disabled"))
    
    def update_text(self, text_widget, name, version, stdout, stderr, return_code):
        """
        更新文本控件
        
        参数:
            text_widget: 文本控件
            name: 包名
            version: 版本约束
            stdout: 标准输出
            stderr: 标准错误
            return_code: 返回码
        """
        # 添加分隔线
        text_widget.insert("end", "-" * 60 + "\n")
        
        # 包名和版本
        package_spec = name
        if version:
            package_spec += version
        
        # 状态
        if return_code == 0:
            status = get_text("success")
            tag = "success"
        else:
            status = get_text("failed")
            tag = "error"
        
        # 创建标签
        if not tag in text_widget.tag_names():
            if tag == "success":
                text_widget.tag_configure(tag, foreground="green")
            else:
                text_widget.tag_configure(tag, foreground="red")
        
        # 添加包信息
        text_widget.insert("end", f"{package_spec}: ", "")
        text_widget.insert("end", f"{status}\n", tag)
        
        # 添加输出
        if stdout:
            text_widget.insert("end", f"{stdout}\n")
        
        # 添加错误
        if stderr:
            text_widget.insert("end", f"{stderr}\n")
        
        # 滚动到底部
        text_widget.see("end")

class ExportRequirementsWindow:
    """导出requirements.txt窗口类"""
    
    def __init__(self, parent, python_path: str):
        """
        初始化导出窗口
        
        参数:
            parent: 父窗口
            python_path: Python解释器路径
        """
        self.parent = parent
        self.python_path = python_path
        self.window = None
        
        # 创建导出窗口
        self.create_export_window()
    
    def create_export_window(self):
        """创建导出窗口"""
        # 如果窗口已存在，不再创建
        if self.window is not None and self.window.winfo_exists():
            self.window.lift()
            return
        
        # 创建导出窗口
        self.window = tk.Toplevel(self.parent)
        self.window.title(get_text("export_requirements"))
        self.window.resizable(False, False)
        
        # 设置为模态窗口
        self.window.transient(self.parent)
        self.window.grab_set()
        
        # 创建主框架
        main_frame = ttk.Frame(self.window, padding=20)
        main_frame.pack(fill="both", expand=True)
        
        # 文件选择框架
        file_frame = ttk.Frame(main_frame)
        file_frame.pack(fill="x", pady=(0, 20))
        
        # 文件路径
        self.file_path_var = tk.StringVar()
        ttk.Label(file_frame, text=get_text("save_as")).pack(side="left", padx=(0, 5))
        ttk.Entry(file_frame, textvariable=self.file_path_var, width=50).pack(side="left", padx=(0, 5), fill="x", expand=True)
        ttk.Button(
            file_frame, 
            text=get_text("browse"),
            command=self.browse_file
        ).pack(side="left")
        
        # Python版本信息
        version = get_python_version(self.python_path)
        version_frame = ttk.Frame(main_frame)
        version_frame.pack(fill="x", pady=(0, 20))
        ttk.Label(
            version_frame,
            text=get_text("python_version_info").format(version),
            font=("", 10)
        ).pack(anchor="w")
        
        # 按钮框架
        button_frame = ttk.Frame(main_frame)
        button_frame.pack(fill="x")
        
        # 导出按钮
        self.export_button = ttk.Button(
            button_frame, 
            text=get_text("export"),
            command=self.export_requirements,
            state="disabled"
        )
        self.export_button.pack(side="left", padx=(0, 5))
        
        # 取消按钮
        ttk.Button(
            button_frame, 
            text=get_text("cancel"),
            command=self.window.destroy
        ).pack(side="right")
        
        # 窗口居中
        self.center_window()
        
        # 绑定关闭事件
        self.window.protocol("WM_DELETE_WINDOW", self.window.destroy)
    
    def center_window(self):
        """使窗口居中显示"""
        self.window.update_idletasks()
        width = self.window.winfo_width()
        height = self.window.winfo_height()
        x = (self.window.winfo_screenwidth() // 2) - (width // 2)
        y = (self.window.winfo_screenheight() // 2) - (height // 2)
        self.window.geometry(f"{width}x{height}+{x}+{y}")
    
    def browse_file(self):
        """浏览文件"""
        file_path = filedialog.asksaveasfilename(
            parent=self.window,
            title=get_text("save_requirements_file"),
            defaultextension=".txt",
            filetypes=[
                (get_text("requirements_files"), "*.txt"),
                (get_text("all_files"), "*.*")
            ]
        )
        
        if file_path:
            self.file_path_var.set(file_path)
            self.export_button.config(state="normal")
    
    def export_requirements(self):
        """导出requirements.txt文件"""
        file_path = self.file_path_var.get()
        
        if not file_path:
            messagebox.showwarning(get_text("warning_msg"), get_text("please_select_save_location"))
            return
        
        # 禁用导出按钮
        self.export_button.config(state="disabled")
        
        # 执行导出
        def export_thread():
            success = export_requirements(self.python_path, file_path)
            
            # 在主线程中显示结果
            if success:
                self.window.after(0, lambda: messagebox.showinfo(
                    get_text("success"),
                    get_text("export_requirements_success").format(file_path)
                ))
                self.window.after(0, self.window.destroy)
            else:
                self.window.after(0, lambda: messagebox.showerror(
                    get_text("error"),
                    get_text("export_requirements_failed")
                ))
                self.window.after(0, lambda: self.export_button.config(state="normal"))
        
        # 启动导出线程
        threading.Thread(target=export_thread, daemon=True).start()

def show_import_requirements_window(parent, python_path: str) -> ImportRequirementsWindow:
    """
    显示导入requirements.txt窗口
    
    参数:
        parent: 父窗口
        python_path: Python解释器路径
        
    返回:
        ImportRequirementsWindow: 导入窗口实例
    """
    # 创建导入窗口
    import_window = ImportRequirementsWindow(parent, python_path)
    return import_window

def show_export_requirements_window(parent, python_path: str) -> ExportRequirementsWindow:
    """
    显示导出requirements.txt窗口
    
    参数:
        parent: 父窗口
        python_path: Python解释器路径
        
    返回:
        ExportRequirementsWindow: 导出窗口实例
    """
    # 创建导出窗口
    export_window = ExportRequirementsWindow(parent, python_path)
    return export_window 